// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SecretClientTasksBackend.DBContexts;

#nullable disable

namespace SecretClientTasksBackend.Migrations
{
    [DbContext(typeof(SCTasksDBContext))]
    [Migration("20240416201336_v1")]
    partial class v1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SecretClientTasksBackend.Models.SCTask", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Gratification")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsTaken")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SCEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SCPhoneNumber")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Voivodeship")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SCTasks");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Address = "Długa 12",
                            City = "Zgierz",
                            Description = "Testowy opis",
                            EndDate = new DateTime(2024, 4, 30, 22, 13, 35, 464, DateTimeKind.Local).AddTicks(719),
                            Gratification = 20.00m,
                            IsTaken = false,
                            Name = "Testowa nazwa zlecenia",
                            SCEmail = "",
                            SCPhoneNumber = -1,
                            StartDate = new DateTime(2024, 4, 16, 22, 13, 35, 464, DateTimeKind.Local).AddTicks(681),
                            Voivodeship = "Łódzkie"
                        },
                        new
                        {
                            Id = 2L,
                            Address = "Cegielniana 27",
                            City = "Łódź",
                            Description = "Testowy opis drugiego zlecenia",
                            EndDate = new DateTime(2024, 4, 30, 22, 13, 35, 464, DateTimeKind.Local).AddTicks(725),
                            Gratification = 13.50m,
                            IsTaken = false,
                            Name = "Testowa nazwa drugiego zlecenia",
                            SCEmail = "",
                            SCPhoneNumber = -1,
                            StartDate = new DateTime(2024, 4, 16, 22, 13, 35, 464, DateTimeKind.Local).AddTicks(724),
                            Voivodeship = "Łódzkie"
                        },
                        new
                        {
                            Id = 3L,
                            Address = "Krótka 6",
                            City = "Ozorków",
                            Description = "Testowy opis, który podobnie jak wyżej jest długi, powiedziałbym nawet, że bardzo długi czy nawet podobny do opisu, który swoją długością przypomina coś jeszcze dłuższego niż to do czego to zostało wcześniej porównane",
                            EndDate = new DateTime(2024, 4, 30, 22, 13, 35, 464, DateTimeKind.Local).AddTicks(730),
                            Gratification = 8.00m,
                            IsTaken = false,
                            Name = "Testowa nazwa zlecenia, które jest trzecie i jest zleceniem, które ma długi opis, bo komuś się chyba najwidoczniej nudziło i jest urodzonym pisarzem",
                            SCEmail = "",
                            SCPhoneNumber = -1,
                            StartDate = new DateTime(2024, 4, 16, 22, 13, 35, 464, DateTimeKind.Local).AddTicks(728),
                            Voivodeship = "Łódzkie"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
